#!/usr/bin/env node
const path = require('path');
const webpack = require('webpack');
const WebpackDevServer = require('webpack-dev-server');
const config = require('./webpack.config');

new WebpackDevServer(webpack(config), {
  contentBase: path.join(__dirname, './dist'),
  publicPath: config.output.publicPath,
  historyApiFallback: true,
  hot: true,
  stats: {
    colors: true
  }
}).listen(4000, 'localhost', function (err) {
  if (err) console.log(err);
  console.log('Listening at localhost:4000');
});
